version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lockbox-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - lockbox-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lockbox-backend
    volumes:
      - ./backend/keys:/app/keys
    environment:
      ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      API_PREFIX: /api/v1
      FRONTEND_BASE: http://frontend:3000
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/lockbox
      JWT_PRIVATE_KEY_PATH: /app/keys/jwt.private.pem
      JWT_PUBLIC_KEY_PATH: /app/keys/jwt_public.pem
      ACCESS_TOKEN_EXPIRES_MINUTES: 15
      REFRESH_TOKEN_EXPIRES_DAYS: 7
      JWT_ALGORITHM: RS256
      JWT_ISSUER: securedataroom
      INVITE_TOKEN_HMAC_SECRET: change-me
      S3_ENDPOINT_URL: http://localstack:4566
      S3_PUBLIC_ENDPOINT_URL: http://localhost:4566
      S3_ACCESS_KEY_ID: test
      S3_SECRET_ACCESS_KEY: test
      S3_BUCKET: lockbox-bucket
      S3_REGION: eu-central-1
      EMAIL_FROM: no-reply@placeholder
      PASSWORD_HASHING_SCHEME: argon2
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    networks:
      - lockbox-net
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: lockbox-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lockbox
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lockbox-net

  localstack:
    image: localstack/localstack:latest
    container_name: lockbox-localstack
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init:/etc/localstack/init/
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lockbox-net

volumes:
  db-data:

networks:
  lockbox-net:
    driver: bridge
