services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lockbox
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init:/etc/localstack/init:ro
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - S3_BUCKET=${S3_BUCKET}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
