"""fix removing orphans

Revision ID: db47478db28f
Revises: 512c63993dfe
Create Date: 2025-10-17 07:18:56.425584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db47478db28f'
down_revision: Union[str, Sequence[str], None] = '512c63993dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shares_invite_id_fkey'), 'shares', type_='foreignkey')
    op.create_foreign_key(None, 'shares', 'invites', ['invite_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.create_foreign_key(op.f('shares_invite_id_fkey'), 'shares', 'invites', ['invite_id'], ['id'])
    # ### end Alembic commands ###
